### ISSUE TITLE
SPI comunication

### ISSUE THREAD

**Issue by SarwarN88** [ElektorLabs/mlx90393-driver#1]
Is there is any possibility to show an example of how I can communicate with this sensor using SPI? Or how I can modify the I2C example code to run in SPI.
Thanks

**Comment by elektor-labs** [comment]
Most of the hard work has been done as the buffer filled for I2C can also be used for SPI. So, in the Arduino example it would be something like the code below in place of the call to ```i2c_write_read``` in the function ```mlx90393_command``` (untested):

```
SPI.beginTransaction(SPISettings(1000000,MSBFIRST,SPI_MODE3));
uint8_t size = max(tx_size,rx_size);
for (uint8_t i=0; i<size; i++)
{
  mlx90393_data_buffer[i] = SPI.transfer(mlx90393_data_buffer[i]);
}
SPI.endTransaction();
return size;

```

**Comment by SarwarN88** [comment]
Thanks for replay. Can you please highlight were I need to change my code in this example to run it in SPI. And How I can increase the clock speed in this code.
Much appreciated,   


#include <Joystick.h>
#include<Wire.h>

// MLX90393 I2C Address is 0x0C(12)
#define Addr 0x0C

Joystick_ Joystick(0x03, //hid report id
JOYSTICK_TYPE_JOYSTICK, //joystick type
32, //button count
0, //Hsw 0-2
false, //x
false, //y
false, //z
false, //rx
false, //ry
false, //rz
true, //rudder
false, //throttle
false, //accelerator
false, //brake
false); //steering

void setup() {
  
  // Initialise I2C communication as MASTER
  Wire.begin();

  // Initialise serial communication, set baud rate = 9600
  Serial.begin(115200);

  // Start I2C Transmission
  Wire.beginTransmission(Addr);
  // Select Write register command
  Wire.write(0x60);
  // Set AH = 0x00, BIST disabled
  Wire.write(0x00);
  // Set AL = 0x5C, Hall plate spinning rate = DEFAULT, GAIN_SEL = 5
  Wire.write(0x5C);
  // Select address register, (0x00 << 2)
  Wire.write(0x00);
  // Stop I2C Transmission
  Wire.endTransmission();

  // Request 1 byte of data
  Wire.requestFrom(Addr, 1);

  // Read status byte
  if (Wire.available() == 1)
  {
    unsigned int c = Wire.read();
  }

  // Start I2C Transmission
  Wire.beginTransmission(Addr);
  // Select Write register command
  Wire.write(0x60);
  // Set AH = 0x02
  Wire.write(0x02);
  // Set AL = 0xB4, RES for magnetic measurement = 0
  Wire.write(0xB0);
  // Select address register, (0x02 << 2)
  Wire.write(0x08);
  // Stop I2C Transmission
  Wire.endTransmission();

  // Request 1 byte of data
  Wire.requestFrom(Addr, 1);

  // Read status byte
  if (Wire.available() == 1)
  {
    unsigned int c = Wire.read();
  }


Joystick.begin();

delay (10);

}



void loop() {

  unsigned int data[7];

  // Start I2C Transmission
  Wire.beginTransmission(Addr);
  // Start single meaurement mode, ZYX enabled
  Wire.write(0x3E);
  // Stop I2C Transmission
  Wire.endTransmission();

  // Request 1 byte of data
  Wire.requestFrom(Addr, 1);

  // Read status byte
  if (Wire.available() == 1)
  {
    unsigned int c = Wire.read();
  }
  delay(7);

  // Start I2C Transmission
  Wire.beginTransmission(Addr);
  // Send read measurement command, ZYX enabled
  Wire.write(0x4E);
  // Stop I2C Transmission
  Wire.endTransmission();

  // Request 7 bytes of data
  Wire.requestFrom(Addr, 7);

  // Read 7 bytes of data
  // status, xMag msb, xMag lsb, yMag msb, yMag lsb, zMag msb, zMag lsb
  if (Wire.available() == 7);
  {
data[0] = Wire.read(); 
data[1] = Wire.read();
data[2] = Wire.read();
data[3] = Wire.read();
data[4] = Wire.read();
data[5] = Wire.read();
data[6] = Wire.read();

  }
  // Convert the data
  int xMag = data[1] * 256 + data[2];
  int yMag = data[3] * 256 + data[4];
  int zMag = data[5] * 256 + data[6];
  
xMag = map(xMag, -32767, 32767, 0, 4095);
yMag = map(yMag, 32767, -32767, 0, 1023);
zMag = map(zMag, 32767, -32767, 0, 1023);


Joystick.setRudder(xMag);


delay(1);
}

**Comment by elektor-labs** [comment]
Use our driver with the mod given before.
Please note that this is not a help forum for problems unrelated to our projects.
